import platform

env = Environment();

if platform.dist()[0] == 'gentoo':
    init_source = 'init.gentoo'
else:
    init_source = 'init.debian'

env.InstallAs(target = '/etc/init.d/cadrolizer', source = init_source)
env.Install('/etc/', 'cadrolizer.conf')
env.Alias('install', [ '/etc/init.d/cadrolizer', '/etc/'])
