env = Environment();

iotivityPath = ARGUMENTS.get('iotivity-path', False)
if iotivityPath == False:
    raise ValueError("'iotivity-path' must be specified")

env.Append(CPPPATH = [
    iotivityPath + '/resource/include/',
    iotivityPath + '/resource/csdk/stack/include',
    iotivityPath + '/resource/csdk/ocsocket/include',
    iotivityPath + '/resource/csdk/ocrandom/include',
    iotivityPath + '/resource/csdk/logger/include',
    iotivityPath + '/resource/csdk/libcoap',
    iotivityPath + '/resource/oc_logger/include'
])

env.Append(CXXFLAGS = ['-std=c++0x', '-Wall'])
env.Prepend(LIBPATH = [ iotivityPath + '/resource/release/obj',
                        iotivityPath + '/resource/csdk/linux/release',
                        iotivityPath + '/resource/oc_logger/lib'
])
env.Append(LIBS = ['oc', 'octbstack', 'oc_logger', '-lpthread', 'boost_program_options'])

cadrolizer = env.Program('cadrolizer', [ 'cadrolizer.cpp', 'CadrolizerResource.cpp',
                                         'os.cpp' ])
cm = env.Program('cadrolizer-manager', 'cadrolizer-manager.cpp')

env.Install('/usr/local/bin', [cadrolizer, cm])
env.Alias('install', '/usr/local/bin')
